export {default as Portfolio} from  './Portfolio'
export {default as Experiences} from './Experiences'
export {default as Critics} from './Critics'
export {default as Collections} from './Collections'
export {default as Contacts} from './Contacts'
export {default as Home} from './Home'